language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r conf/dev_requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python manage.py test addresses events galleries games groups players positions seasons statistics teams tournaments
  - coverage run manage.py test addresses events galleries games groups players positions seasons statistics teams tournaments
after_success: coveralls